services:
  - type: web
    name: attendance-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: attendance-db
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production

databases:
  - name: attendance-db
    databaseName: enhanced_attendance_system
    user: attendance_user
    plan: free
